apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gradio-chart.fullname" . }}-deployment
  labels:
    {{- include "gradio-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      {{- include "gradio-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "gradio-chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Values.app.name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.targetPort }}
          name: http
        resources:
          {{- toYaml .Values.deployment.resources | nindent 10 }}
