services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - celery_network
  api: 
    build: ./api
    ports:
      - 8001:8000
    depends_on:
      - redis
    networks:
      - celery_network
    volumes:
      - ../.cursor:/app/.cursor

  worker:
    build: ./worker
    depends_on:
      - redis
    networks:
      - celery_network
    volumes:
      - ./worker_data:/data
      - ../.cursor:/app/.cursor
networks:
  celery_network:
    driver: bridge
